name: bmi_calcu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hexcolor: ^2.0.6  

flutter:

  uses-material-design: true

  assets:
   - images/
  #   - images/a_dot_ham.jpeg

  
  fonts:
    - family: dana
      fonts:
        - asset: fonts/dm.ttf
  #       - asset: fonts/Schyler-Italic.ttf